### ISSUE TITLE
"Error while checking Authentication: Error: no JSON"

### ISSUE THREAD

**Issue by Babelbernd** [Apollon77/alexa-remote#106]
Hello all, 

anybody facing issues with login initialisation? Till yesterday everything was working fine but suddenly i had to reinitialise my account. With cookies it was not working so i tried the other 2 options but i'm having same issues. 

I think amazon has changed something in logging in or is it just me having problems?

Thanks in advance, Michael

**Comment by Babelbernd** [comment]
However after i said to me i will try it one last time today it suddenly was working again. The only thing that is not working is the "On device activity" node. My Alexa is just not listening what i'm saying. There is not even a message on a debug node.

**Comment by Apollon77** [comment]
you use the most uptodate version??

**Comment by Babelbernd** [comment]
Yes i do, when i open Node-Red and Insert a Node "on device Activity" IT just says "listening" but it doesnt listen at all.

**Comment by Apollon77** [comment]
I can not tell anything about the node.red node. sorry. The NEW library version is working - which is proofed by many users (and me)

**Comment by Apollon77** [comment]
In fact I need more debaug level log

**Comment by Babelbernd** [comment]
Unfortunately there is no debug Message. Maybe there is another one who is facing same issues as me?

**Comment by ammawel** [comment]
In node-red, the problems are mainly manifested by Alexe not speaking after some time and not responding to devices-activities as mentioned above.
Unfortunately the developer of the node-red-flow has disappeared.
Maybe the following information will help

- it is important to use the proxy-login in node-red-contrib-alexa-remote
- node-red controls the refresh time itself
- the alexa-remote-api is initialized by node-red from line 415 in alexa-remote-account.js with 
`config.refreshCookieInterval = 0;`
`config.proxyLogLevel = 'warn';`
`config.cookieJustCreated = true; // otherwise it just tries forever...`
`config.bluetooth = false;`
`config.setupProxy = false;`
- everything works for 24 hours
- the next refresh by node-red after these 24 hours makes the Alexa voice functions stop working
- you can change this 24-hour period in which it works in line 123 of alexa-remote.js
`if (tokensValidSince < 24 * 60 * 60 * 1000) {
`

Thanks for any help
Achim

**Comment by Apollon77** [comment]
Really only 24h?? in iobroker adapter I do the refresh after 7 days and that works completely fine. Also 10 is ok normally. strange
