### ISSUE TITLE
Exponential Backoff Reconnect Logic is Incorrect

### ISSUE THREAD

**Issue by DanPatten** [Apollon77/alexa-remote#213]
**Describe the bug**  
On http2-push close it disconnects and then tries to reconnect using the retry logic. However upon successful reconnect we do not properly reset the value of the retry delay.

My logs, for some reason this occurs about every minute or so, you will notice the retry connection logic. If I hardcode retryDelay = 1 it appears to work properly.
```
29 Sep 19:19:01 - [debug] [alexa-remote-account:xx] Alexa-Remote: 0 entries left in activity queue
29 Sep 19:19:29 - [debug] [alexa-remote-account:xx] Alexa-Remote HTTP2-PUSH: Close: undefined: undefined
29 Sep 19:19:29 - [debug] [alexa-remote-account:xx] Alexa-Remote HTTP2-PUSH: Retry Connection in 1s
29 Sep 19:19:30 - [debug] [alexa-remote-account:xx] Alexa-Remote: Update access token ...
29 Sep 19:19:30 - [debug] [alexa-remote-account:xx] Alexa-Remote HTTP2-PUSH: Use host bob-dispatch-prod-na.amazon.com
29 Sep 19:19:30 - [debug] [alexa-remote-account:xx] Alexa-Remote HTTP2-PUSH: Initialization completed

```
**To Reproduce**  
Unknown - happens randomly

**Expected behavior**  
When 'Initialization completed' is fired I would expect the retry counter to reset to 0 since there is a valid connection, need to verify this works everywhere.

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 6.1.2
 - JS-Controller version: ?
 - Node version: 18.7.1
 - Operating system: raspberry pi OS - on Home Assistant

**Comment by Apollon77** [comment]
Do you have a longer log please to show exactly the issue?

**Comment by danielbrunt57** [comment]
> 29 Sep 19:19:29 - [debug] [alexa-remote-account:xx] Alexa-Remote HTTP2-PUSH: Close: undefined: undefined

@Apollon77 
Ingo, This is same thing I see in my Node-RED installation when I "deploy changes" or "restart flows".  In NR, the "initialise" has to re-occur following those actions but it seems to start up another HTTP2Push connection despite the first one still active but now "undefined"?  When the first one (now undefined?) closes, the library retries that "undefined" connection which succeeds but then it closes again.  Is there a retry counter before abandoning it and leaving it closed?

I think if an "undefined" connection closes, it should stay closed and not retry?

I have to restart NR to kill the existing HTTP2Push connection so that the flow can start afresh.

Not sure if the library can address this anomaly or if the fix has to somehow occur in the Node-RED "applestrudel" package...

**Comment by Apollon77** [comment]
Does your flow correctly tears down Alexa remote before starting anew? Because seems that's not the case?!

**Comment by danielbrunt57** [comment]
There aren't any nodes in applestrudel with a terminate function, just `initialise`, `fresh authentication`, `refresh cookie`, `update cached state`, `reset` & `interval info` and I've not delved inside NR to understand what I might have available to work with when deploying/restarting flows.  Does the library provide a call for terminating connections?

**Comment by Apollon77** [comment]
sure :-)) https://github.com/Apollon77/alexa-remote/blob/master/alexa-remote.js#L939
